// Shared affiliate training is plain text. Financial terms remain authoritative.
const DEFAULTS = Object.freeze({
 title:'Tools to turn conversations into signups',
 guidance:'Start with a business need. Ask whether they are finding deals, looking for buyers or organizing follow-ups. Introduce one relevant Better tool, invite them to try a free account, then review current plans when paid access fits their workflow.',
 sourcing:'Zillow: look for public listing business contacts who may need another place to share a property and connect with buyers. Ask whether they work with off-market opportunities before introducing Better.\nInvestor Base: approach investors through permitted contact channels and ask about their market and buying criteria. Explain how property posts and real estate connections could fit their search.\nFacebook: join local investor, wholesaler and real estate groups. Follow group rules, answer relevant questions and ask permission before moving a conversation to a signup link.\nAlso consider local REIA communities, real estate meetups, LinkedIn and professional directories. Use public business contacts or permission-based introductions, honor opt-outs and do not scrape listings or send bulk unsolicited messages. Better does not supply a lead list here.',
 callScript:'Hi, this is [your name], a Better Real Estate affiliate. Are you currently buying, selling or wholesaling off-market properties? What is harder right now: finding opportunities, connecting with buyers, or keeping deal follow-ups organized? Better is free to join and brings property posts, real estate connections and deal conversations into one workspace. If that fits your business, can I send you a link to try it?',
 shareScript:'If you work off market, take a look at Better Real Estate. It’s free to join: post a property, connect with buyers and keep deal conversations together. {link}'
});
const LIMITS={title:120,guidance:4000,sourcing:6000,callScript:4000,shareScript:4000};
function read(db){const r=(db.affiliateContent||[]).find(x=>x.id==='current');return {...DEFAULTS,...r,id:'current',revision:Number(r?.revision||0)};}
function validate(body){const fields={};for(const [key,max] of Object.entries(LIMITS)){const value=body?.[key];if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${key} must contain 1–${max} characters.`);fields[key]=value.trim();}return fields;}
const SAVE_SQL=`INSERT INTO kv_affiliatecontent(id,data,updated_at)
 SELECT 'current',$1::jsonb,now() WHERE $2::bigint=0 OR EXISTS(SELECT 1 FROM kv_affiliatecontent WHERE id='current')
 ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=now()
 WHERE (kv_affiliatecontent.data->>'revision')::bigint=$2::bigint RETURNING data`;
function writer(store){let tail=Promise.resolve();const run=async(body,userId)=>{const fields=validate(body);if(!Number.isSafeInteger(body.revision)||body.revision<0)throw new Error('Invalid content revision.');const db=await store.loadDB();const current=read(db);if(current.revision!==body.revision)return null;const row={...fields,id:'current',revision:current.revision+1,updatedAt:new Date().toISOString(),updatedBy:userId};if(store.FILE_MODE){db.affiliateContent=[row];await store.saveDB(db);return row;}await store.init();const rows=await store.sql(SAVE_SQL,[JSON.stringify(row),body.revision]);return rows[0]?.data||null;};return (body,userId)=>{if(!store.FILE_MODE)return run(body,userId);const task=tail.then(()=>run(body,userId));tail=task.catch(()=>{});return task;};}
module.exports={DEFAULTS,LIMITS,read,validate,writer,SAVE_SQL};
