/* Better Real Estate property evidence adapters.
   v29.13: evidence-first property identity, source consensus, exact-match checks,
   authorized RESO MLS, Regrid parcel facts and OpenAI web research.
   No direct website scraping. Weak/conflicting facts are preserved as evidence
   but are NOT promoted to verified subject facts. */

const inFlightResearch = new Map();

function clean(v,n=500){return String(v??'').trim().slice(0,n)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function esc(v){return String(v).replace(/'/g,"''")}
function first(...v){return v.find(x=>x!==undefined&&x!==null&&x!=='')??null}
function hav(a,b,c,d){if([a,b,c,d].some(x=>!Number.isFinite(Number(x))))return null;const R=3958.8,rad=x=>Number(x)*Math.PI/180,dLat=rad(c-a),dLon=rad(d-b),q=Math.sin(dLat/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}

const STREET_SUFFIX = new Map(Object.entries({street:'st',st:'st',avenue:'ave',ave:'ave',road:'rd',rd:'rd',drive:'dr',dr:'dr',lane:'ln',ln:'ln',court:'ct',ct:'ct',boulevard:'blvd',blvd:'blvd',place:'pl',pl:'pl',terrace:'ter',ter:'ter',parkway:'pkwy',pkwy:'pkwy',highway:'hwy',hwy:'hwy',circle:'cir',cir:'cir',trail:'trl',trl:'trl',way:'way'}));
function normText(v){return clean(v,400).toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function streetTokens(v){return normText(v).split(' ').filter(Boolean).map(x=>STREET_SUFFIX.get(x)||x).filter(x=>!['unit','apt','apartment','#'].includes(x))}
function parseAddress(address){
  const raw=clean(address,300),parts=raw.split(',').map(x=>x.trim()).filter(Boolean),street=parts[0]||raw;
  const zip=(raw.match(/\b\d{5}(?:-\d{4})?\b/)||[])[0]||'';
  const state=((raw.match(/(?:,|\s)\s*([A-Za-z]{2})(?=\s*(?:,|\d{5}|$))/)||[])[1]||'').toUpperCase();
  let city='';
  if(parts.length>=2){const stateIx=parts.findIndex(x=>new RegExp(`^${state || '[A-Za-z]{2}'}(?:\\s+\\d{5})?$`,'i').test(x));city=stateIx>0?parts[stateIx-1]:parts[1]}
  const toks=streetTokens(street),houseNumber=(toks.find(x=>/^\d+[a-z]?$/.test(x))||'').toLowerCase();
  return {raw,street,city,state,zip,houseNumber,streetTokens:toks.filter(x=>x!==houseNumber)};
}
function cacheKey(address){return normText(address).replace(/\b(street|avenue|road|drive|lane|court|boulevard|place|terrace|parkway|highway|circle|trail)\b/g,m=>STREET_SUFFIX.get(m)||m)}
function recordAddress(rec={}){return [rec.address,rec.city,rec.state,rec.postalCode].filter(Boolean).join(', ')}
function addressMatchScore(inputAddress,record={}){
  const a=typeof inputAddress==='string'?parseAddress(inputAddress):inputAddress;
  const b=parseAddress(recordAddress(record));
  let score=0;
  if(a.houseNumber){if(b.houseNumber===a.houseNumber)score+=35;else if(b.houseNumber)return -100}
  if(a.streetTokens.length){const A=new Set(a.streetTokens),B=new Set(b.streetTokens),hit=[...A].filter(x=>B.has(x)).length,ratio=hit/Math.max(1,A.size);score+=ratio>=.8?30:ratio>=.5?20:ratio>=.3?8:-20}
  if(a.city&&b.city)score+=normText(a.city)===normText(b.city)?15:-12;
  if(a.state&&b.state)score+=a.state===b.state?10:-25;
  if(a.zip&&b.zip)score+=a.zip.slice(0,5)===b.zip.slice(0,5)?10:-20;
  return score;
}

function configs(){const out=[];if(process.env.MLS_RESO_BASE_URL&&process.env.MLS_RESO_TOKEN)out.push({name:clean(process.env.MLS_RESO_NAME||'Authorized MLS',80),base:clean(process.env.MLS_RESO_BASE_URL,600),token:clean(process.env.MLS_RESO_TOKEN,2000)});if(process.env.MLS_RESO_SOURCES_JSON){try{for(const x of JSON.parse(process.env.MLS_RESO_SOURCES_JSON)||[]){if(x?.name&&x?.baseUrl&&x?.token)out.push({name:clean(x.name,80),base:clean(x.baseUrl,600),token:clean(x.token,2000)})}}catch{}}return out.filter((x,i,a)=>a.findIndex(y=>y.base===x.base)===i)}
function normMls(r,source){return {source,sourceKey:`mls:${normText(source)}`,sourceType:'MLS / RESO',verification:'authorized-listing-feed',listingKey:clean(r.ListingKey||r.ListingId||'',120)||null,address:clean(r.UnparsedAddress||[r.StreetNumber,r.StreetName,r.StreetSuffix].filter(Boolean).join(' '),250)||null,city:clean(r.City,100)||null,state:clean(r.StateOrProvince,40)||null,postalCode:clean(r.PostalCode,20)||null,status:clean(r.StandardStatus||r.MlsStatus,60)||null,listPrice:num(r.ListPrice),salePrice:num(r.ClosePrice),saleDate:r.CloseDate||null,bedrooms:num(r.BedroomsTotal),bathrooms:num(r.BathroomsTotalInteger??r.BathroomsFull),squareFootage:num(r.LivingArea),lotSize:num(r.LotSizeSquareFeet),yearBuilt:num(r.YearBuilt),propertyType:clean(r.PropertyType||r.PropertySubType,100)||null,daysOnMarket:num(r.DaysOnMarket),remarks:clean(r.PublicRemarks,1200)||null,latitude:num(r.Latitude),longitude:num(r.Longitude),sourceUpdatedAt:r.ModificationTimestamp||null,retrievedAt:new Date().toISOString()}}
async function queryMls(cfg,filter,top=100){const base=cfg.base.replace(/\/$/,''),fields=['ListingKey','ListingId','UnparsedAddress','StreetNumber','StreetName','StreetSuffix','City','StateOrProvince','PostalCode','StandardStatus','MlsStatus','ListPrice','ClosePrice','CloseDate','BedroomsTotal','BathroomsTotalInteger','BathroomsFull','LivingArea','LotSizeSquareFeet','YearBuilt','PropertyType','PropertySubType','DaysOnMarket','PublicRemarks','Latitude','Longitude','ModificationTimestamp'].join(','),u=new URL(base+'/Property');u.searchParams.set('$filter',filter);u.searchParams.set('$select',fields);u.searchParams.set('$top',String(top));const r=await fetch(u,{headers:{Authorization:`Bearer ${cfg.token}`,Accept:'application/json'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`${cfg.name} returned ${r.status}`);const j=await r.json();return (Array.isArray(j.value)?j.value:[]).map(x=>normMls(x,cfg.name))}
function bestSubject(rows,address){const scored=(rows||[]).map(x=>({...x,addressMatchScore:addressMatchScore(address,x)})).sort((a,b)=>b.addressMatchScore-a.addressMatchScore);return scored[0]?.addressMatchScore>=65?scored[0]:null}

function regridFields(feature){const p=feature?.properties||{},f=p.fields||p;return {...f,ll_uuid:first(f.ll_uuid,p.ll_uuid),path:first(f.path,p.path)}}
function normRegrid(feature){const f=regridFields(feature);return {source:'Regrid',sourceKey:'regrid',sourceType:'County / parcel records',verification:'public-record-aggregator',parcelId:first(f.parcelnumb,f.state_parcelnumb,f.ll_uuid),address:first(f.address,f.situs_address,f.headline),city:first(f.scity,f.city),state:first(f.state2,f.state),postalCode:first(f.szip,f.zip),bedrooms:num(first(f.num_bedrooms,f.bedrooms)),bathrooms:num(first(f.num_bath,f.bathrooms)),squareFootage:num(first(f.recrdareano,f.area_building)),lotSize:num(first(f.sqft,f.ll_gissqft,f.lot_sqft)),yearBuilt:num(f.yearbuilt),propertyType:first(f.usedesc,f.usecode,f.structstyle),salePrice:num(f.saleprice),saleDate:first(f.saledate,f.sale_date),assessedValue:num(first(f.parval,f.assessedval,f.assessed_value)),landValue:num(f.landval),improvementValue:num(f.improvval),taxAmount:num(first(f.taxamt,f.tax_amount)),zoning:first(f.zoning_description,f.zoning),owner:first(f.owner),latitude:num(first(f.lat,f.latitude)),longitude:num(first(f.lon,f.longitude)),sourceRecordUrl:first(f.sourceurl,f.source_url),sourceUpdatedAt:first(f.ll_last_refresh,f.ll_updated_at),retrievedAt:new Date().toISOString(),rawFieldCount:Object.keys(f).length}}
function selectRegridFeature(features,address){const ranked=(features||[]).map((feature,index)=>{const subject=normRegrid(feature),score=addressMatchScore(address,subject);return {feature,subject,score,index}}).sort((a,b)=>b.score-a.score||a.index-b.index);const best=ranked[0]||null;return {subject:best&&best.score>=65?{...best.subject,addressMatchScore:best.score}:null,matchScore:best?.score??null,candidates:ranked.slice(0,5).map(x=>({address:recordAddress(x.subject),parcelId:x.subject.parcelId||null,score:x.score}))}}
async function researchRegrid(address){const token=clean(process.env.REGRID_API_TOKEN||process.env.REGRID_TOKEN,3000);if(!token)return {configured:false,subject:null,error:null,candidates:[]};const u=new URL('https://app.regrid.com/api/v2/parcels/address');u.searchParams.set('query',address);u.searchParams.set('limit','5');u.searchParams.set('return_custom','false');u.searchParams.set('return_geometry','false');u.searchParams.set('return_matched_buildings','false');u.searchParams.set('return_enhanced_ownership','false');u.searchParams.set('return_zoning','false');const r=await fetch(u,{headers:{Accept:'application/json','x-regrid-token':token},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`Regrid returned ${r.status}`);const j=await r.json(),features=j?.parcels?.features||j?.features||[],picked=selectRegridFeature(features,address);return {configured:true,subject:picked.subject,error:picked.subject?null:(features.length?'Regrid returned parcels, but none matched the entered address strongly enough.':'No Regrid parcel matched this address.'),count:features.length,matchScore:picked.matchScore,candidates:picked.candidates}}

function extractText(payload){for(const item of payload?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&c.text)return c.text;return ''}
function webSources(payload){const urls=[];for(const item of payload?.output||[]){if(item?.type==='web_search_call')for(const s of item?.action?.sources||[])if(s?.url)urls.push(s.url);for(const c of item?.content||[])for(const a of c?.annotations||[])if(a?.url)urls.push(a.url)}return [...new Set(urls)].slice(0,40)}
function canonicalUrl(v){try{const u=new URL(v);return `${u.protocol}//${u.hostname.toLowerCase()}${u.pathname.replace(/\/$/,'')}`}catch{return ''}}
function urlWasActuallySearched(url,sources){const c=canonicalUrl(url);return !!c&&(sources||[]).some(s=>{const x=canonicalUrl(s);return x===c||x.startsWith(c)||c.startsWith(x)})}
function webReliability(kind){return ({county_assessor:90,public_record:86,broker_listing:80,real_estate_portal:70,other:55})[kind]||55}
async function researchWeb(address){
  const key=clean(process.env.OPENAI_API_KEY,3000);if(!key)return {configured:false,facts:null,factEvidence:[],comps:[],sources:[],error:null};
  const schema={type:'object',additionalProperties:false,required:['factEvidence','soldComps','marketContext','notes'],properties:{factEvidence:{type:'array',maxItems:28,items:{type:'object',additionalProperties:false,required:['field','numberValue','textValue','subjectAddress','sourceUrl','sourceName','sourceKind'],properties:{field:{type:'string',enum:['bedrooms','bathrooms','squareFootage','yearBuilt','propertyType','lastSalePrice','lastSaleDate']},numberValue:{anyOf:[{type:'number'},{type:'null'}]},textValue:{anyOf:[{type:'string'},{type:'null'}]},subjectAddress:{type:'string'},sourceUrl:{type:'string'},sourceName:{type:'string'},sourceKind:{type:'string',enum:['county_assessor','public_record','broker_listing','real_estate_portal','other']}}}},soldComps:{type:'array',maxItems:12,items:{type:'object',additionalProperties:false,required:['address','salePrice','saleDate','bedrooms','bathrooms','squareFootage','yearBuilt','propertyType','sourceUrl'],properties:{address:{type:'string'},salePrice:{type:'number'},saleDate:{type:'string'},bedrooms:{anyOf:[{type:'number'},{type:'null'}]},bathrooms:{anyOf:[{type:'number'},{type:'null'}]},squareFootage:{anyOf:[{type:'number'},{type:'null'}]},yearBuilt:{anyOf:[{type:'number'},{type:'null'}]},propertyType:{anyOf:[{type:'string'},{type:'null'}]},sourceUrl:{type:'string'}}}},marketContext:{type:'array',maxItems:10,items:{type:'object',additionalProperties:false,required:['address','status','price','sourceUrl'],properties:{address:{type:'string'},status:{type:'string'},price:{anyOf:[{type:'number'},{type:'null'}]},sourceUrl:{type:'string'}}}},notes:{type:'array',maxItems:8,items:{type:'string'}}}};
  const body={model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high'}],tool_choice:'required',instructions:[
    'Research the exact residential property address using public web search. Evidence quality matters more than completeness.',
    'For bedrooms, bathrooms, living square footage and year built, seek at least TWO independent sources when possible. Prefer county/assessor/public records, authorized or broker-published listing pages, then reputable real-estate portals.',
    'Return one factEvidence item PER source PER field. Do not merge conflicting values. Do not infer bedrooms from room count, bathrooms from fixture counts, living area from lot size/building footprint, or year built from renovation dates.',
    'Every factEvidence subjectAddress must be the exact property the source describes. Every sourceUrl must be a URL actually surfaced by web search. Return null/omit evidence rather than guessing.',
    'Search recent nearby SOLD comparable properties separately. Active/pending listings are market context only, never sold comps. A sold comp needs exact address, closed sale price, sale date and a source URL.',
    'Do not bypass paywalls, authentication, robots controls or access restrictions.'
  ].join('\n'),input:`Subject property: ${address}`,text:{format:{type:'json_schema',name:'better_property_web_research',schema,strict:true}},max_output_tokens:2200};
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Web research failed (${r.status}): ${clean(j?.error?.message||'unknown error',180)}`);let parsed=null;try{parsed=JSON.parse(extractText(j))}catch{};const sources=webSources(j);if(!parsed)return {configured:true,facts:null,factEvidence:[],comps:[],sources,error:'Web research returned no structured evidence.'};
  const factEvidence=(parsed.factEvidence||[]).filter(x=>urlWasActuallySearched(x.sourceUrl,sources)&&addressMatchScore(address,{address:x.subjectAddress})>=55).map(x=>{const value=x.field==='propertyType'||x.field==='lastSaleDate'?clean(x.textValue,120):num(x.numberValue);return {field:x.field,value,subjectAddress:clean(x.subjectAddress,250),source:`Web · ${clean(x.sourceName,80)||'source'}`,sourceKey:`web:${(()=>{try{return new URL(x.sourceUrl).hostname.replace(/^www\./,'').toLowerCase()}catch{return clean(x.sourceName,80).toLowerCase()}})()}`,sourceType:'Public web',sourceKind:x.sourceKind,reliability:webReliability(x.sourceKind),sourceUrl:x.sourceUrl,verification:'web-source-specific',retrievedAt:new Date().toISOString()}}).filter(x=>x.value!==null&&x.value!==undefined&&x.value!=='');
  const facts={};for(const f of factEvidence){if(facts[f.field]===undefined)facts[f.field]=f.value}
  const comps=(parsed.soldComps||[]).filter(x=>urlWasActuallySearched(x.sourceUrl,sources)).map(x=>({...x,source:'Public web research',sourceKey:`web:${(()=>{try{return new URL(x.sourceUrl).hostname.replace(/^www\./,'').toLowerCase()}catch{return 'unknown'}})()}`,sourceType:'Public web',verification:'web-corroborated',retrievedAt:new Date().toISOString()}));
  const marketContext=(parsed.marketContext||[]).filter(x=>urlWasActuallySearched(x.sourceUrl,sources));
  return {configured:true,facts,factEvidence,comps,marketContext,notes:parsed.notes||[],sources,error:null};
}

function validFieldValue(field,value){if(value===null||value===undefined||value==='')return false;if(field==='bedrooms')return Number.isFinite(Number(value))&&Number(value)>=0&&Number(value)<=20;if(field==='bathrooms')return Number.isFinite(Number(value))&&Number(value)>=0&&Number(value)<=20;if(field==='squareFootage')return Number.isFinite(Number(value))&&Number(value)>=200&&Number(value)<=50000;if(field==='yearBuilt')return Number.isFinite(Number(value))&&Number(value)>=1700&&Number(value)<=new Date().getFullYear()+1;if(field==='propertyType')return clean(value,100).length>1;return true}
function normPropertyType(v){const s=normText(v);if(/single.*family|detached|sfr/.test(s))return 'single family';if(/multi.*family|duplex|triplex|fourplex/.test(s))return 'multi family';if(/condo/.test(s))return 'condo';if(/town/.test(s))return 'townhouse';if(/mobile|manufactured/.test(s))return 'mobile home';if(/land|vacant/.test(s))return 'land';if(/commercial/.test(s))return 'commercial';return s}
function sameValue(field,a,b){if(field==='squareFootage'){const x=Number(a),y=Number(b);return Math.abs(x-y)<=Math.max(75,Math.max(x,y)*.05)}if(field==='bathrooms')return Math.abs(Number(a)-Number(b))<.26;if(field==='bedrooms'||field==='yearBuilt')return Number(a)===Number(b);if(field==='propertyType')return normPropertyType(a)===normPropertyType(b);return String(a)===String(b)}
function evidenceLabel(e){return {source:e.source,sourceType:e.sourceType,sourceUrl:e.sourceUrl||e.sourceRecordUrl||null,value:e.value,reliability:e.reliability}}
function resolveField(field,evidence){
  const items=evidence.filter(e=>validFieldValue(field,e.value));if(!items.length)return {field,value:null,status:'missing',confidence:'Low',sources:[],alternatives:[]};
  const groups=[];for(const item of items){let g=groups.find(x=>sameValue(field,x.value,item.value));if(!g){g={value:item.value,items:[],weight:0,sourceKeys:new Set()};groups.push(g)}g.items.push(item);g.weight+=item.reliability||50;g.sourceKeys.add(item.sourceKey||item.source)}
  groups.sort((a,b)=>b.weight-a.weight||b.sourceKeys.size-a.sourceKeys.size);const win=groups[0],runner=groups[1];
  const independent=win.sourceKeys.size;
  // v29.13 truth rule: core subject facts are never promoted from one source alone,
  // even an authorized MLS record. A single source remains useful evidence, but the
  // user explicitly prefers a blank/needs-confirmation state over a confidently wrong fact.
  const strongConsensus=independent>=2&&( !runner || win.weight>=runner.weight*1.35 || win.sourceKeys.size>runner.sourceKeys.size );
  const value=strongConsensus?win.value:null;
  const status=value!==null?(runner?'verified_with_conflict':'verified'):(runner?'conflicting':'single_source');
  const confidence=value!==null?(independent>=3?'High':'Moderate'):'Low';
  return {field,value,status,confidence,sources:win.items.map(evidenceLabel),alternatives:groups.slice(1).map(g=>({value:g.value,sources:g.items.map(evidenceLabel)})),raw:items.map(evidenceLabel)};
}
function sourceEvidenceForField(field,mlsSubject,regridSubject,web){const out=[];if(mlsSubject&&validFieldValue(field,mlsSubject[field]))out.push({value:mlsSubject[field],source:mlsSubject.source,sourceKey:mlsSubject.sourceKey||`mls:${mlsSubject.source}`,sourceType:'MLS / RESO',sourceUrl:null,reliability:100});if(regridSubject&&validFieldValue(field,regridSubject[field]))out.push({value:regridSubject[field],source:'Regrid',sourceKey:'regrid',sourceType:'County / parcel records',sourceUrl:regridSubject.sourceRecordUrl||null,reliability:85});for(const x of web?.factEvidence||[])if(x.field===field)out.push(x);return out}
function resolveSubjectEvidence({mlsSubject=null,regridSubject=null,web=null,address}){
  const fields=['bedrooms','bathrooms','squareFootage','yearBuilt','propertyType'];const fieldEvidence={};const subject={address,source:'Cross-checked evidence',sourceType:'Verified consensus',retrievedAt:new Date().toISOString()};
  const identitySource=mlsSubject||regridSubject||null;if(identitySource){subject.address=identitySource.address||address;subject.city=identitySource.city||null;subject.state=identitySource.state||null;subject.postalCode=identitySource.postalCode||null;subject.parcelId=identitySource.parcelId||null;subject.latitude=identitySource.latitude??null;subject.longitude=identitySource.longitude??null;subject.sourceUpdatedAt=identitySource.sourceUpdatedAt||null}
  for(const field of fields){const resolved=resolveField(field,sourceEvidenceForField(field,mlsSubject,regridSubject,web));fieldEvidence[field]=resolved;subject[field]=resolved.value}
  const conflicts=Object.values(fieldEvidence).filter(x=>x.status==='conflicting'||x.status==='verified_with_conflict').map(x=>({field:x.field,status:x.status,selected:x.value,values:[...new Set((x.raw||[]).map(y=>y.value))],evidence:x.raw||[]}));
  const resolvedCore=fields.filter(f=>subject[f]!==null&&subject[f]!==undefined&&subject[f]!=='').length;
  const addressScore=Math.max(mlsSubject?.addressMatchScore??-Infinity,regridSubject?.addressMatchScore??-Infinity);const matched=Number.isFinite(addressScore)&&addressScore>=65;
  const confidence=matched&&resolvedCore>=4?'High':matched&&resolvedCore>=2?'Moderate':'Low';
  return {subject,fieldEvidence,conflicts,identity:{addressMatched:matched,addressMatchScore:Number.isFinite(addressScore)?addressScore:null,resolvedCoreFields:resolvedCore,confidence,sufficientForValuation:matched&&resolvedCore>=2}};
}

async function researchFresh(address){
  const parsed=parseAddress(address),errors=[],allSubjects=[],allComps=[],sources=[];
  const mlsJobs=configs().map(async cfg=>{sources.push({name:cfg.name,type:'Authorized MLS / RESO Web API'});try{const clauses=[];if(parsed.street)clauses.push(`contains(tolower(UnparsedAddress),'${esc(parsed.street.toLowerCase())}')`);if(parsed.city)clauses.push(`tolower(City) eq '${esc(parsed.city.toLowerCase())}'`);if(parsed.state)clauses.push(`StateOrProvince eq '${esc(parsed.state.toUpperCase())}'`);const rows=await queryMls(cfg,clauses.join(' and '),15),subject=bestSubject(rows,address),comps=[];if(subject){const c=[];if(subject.city)c.push(`tolower(City) eq '${esc(subject.city.toLowerCase())}'`);if(subject.state)c.push(`StateOrProvince eq '${esc(subject.state.toUpperCase())}'`);c.push(`StandardStatus eq 'Closed'`);for(const x of await queryMls(cfg,c.join(' and '),100)){if(x.listingKey&&x.listingKey===subject.listingKey)continue;x.distanceMiles=hav(subject.latitude,subject.longitude,x.latitude,x.longitude);if(x.salePrice&&(!x.distanceMiles||x.distanceMiles<=5))comps.push(x)}}return {subject,comps}}catch(e){errors.push({source:cfg.name,error:clean(e.name==='TimeoutError'?'Timed out after 10 seconds.':e.message,180)});return {subject:null,comps:[]}}});
  const regridJob=(async()=>{try{const r=await researchRegrid(address);if(r.configured)sources.push({name:'Regrid',type:'County / parcel records'});if(r.error)errors.push({source:'Regrid',error:r.error});return r}catch(e){errors.push({source:'Regrid',error:clean(e.name==='TimeoutError'?'Timed out after 8 seconds.':e.message,180)});return {configured:Boolean(process.env.REGRID_API_TOKEN||process.env.REGRID_TOKEN),subject:null,candidates:[]}}})();
  const webJob=(async()=>{try{const w=await researchWeb(address);if(w.configured)sources.push({name:'Better Web Research',type:'Public web search'});return w}catch(e){errors.push({source:'Better Web Research',error:clean(e.name==='TimeoutError'?'Timed out after 20 seconds; analysis can continue with property/MLS evidence.':e.message,180)});return {configured:Boolean(process.env.OPENAI_API_KEY),facts:null,factEvidence:[],comps:[],sources:[],marketContext:[]}}})();
  const [regrid,web,mlsResults]=await Promise.all([regridJob,webJob,Promise.all(mlsJobs)]);
  if(regrid.subject)allSubjects.push(regrid.subject);for(const m of mlsResults){if(m.subject)allSubjects.unshift(m.subject);allComps.push(...m.comps)}allComps.push(...(web.comps||[]));
  const mlsSubject=allSubjects.find(x=>x.sourceType==='MLS / RESO')||null;const resolved=resolveSubjectEvidence({mlsSubject,regridSubject:regrid.subject,web,address});const subject=resolved.subject,seen=new Set(),comps=allComps.filter(x=>{const k=x.listingKey||`${clean(x.address).toLowerCase()}|${x.salePrice}|${x.saleDate}`;if(!x.salePrice||seen.has(k))return false;seen.add(k);if(subject?.latitude&&subject?.longitude&&x.latitude&&x.longitude)x.distanceMiles=hav(subject.latitude,subject.longitude,x.latitude,x.longitude);return true}).sort((a,b)=>(a.distanceMiles??99)-(b.distanceMiles??99)).slice(0,30);
  return {configured:sources.length>0,sourceCount:sources.length,sources,subject,fieldEvidence:resolved.fieldEvidence,identity:resolved.identity,rawSubjects:{mls:mlsSubject||null,regrid:regrid.subject||null,regridCandidates:regrid.candidates||[]},comps,marketContext:web.marketContext||[],webSources:web.sources||[],conflicts:resolved.conflicts,errors,retrievedAt:new Date().toISOString(),notice:`Research checked ${sources.map(x=>x.name).join(', ')||'no live sources'}. ${configs().length?'Authorized MLS feeds were queried.':'No authorized MLS feed is configured.'} ${regrid.configured?'Regrid parcel records were queried with exact-address match checks.':'Regrid is not configured.'} ${web.configured?'Public web research was attempted with source-specific fact evidence.':'Web research was unavailable.'}`};
}
async function research(address){const key=cacheKey(address);if(inFlightResearch.has(key))return inFlightResearch.get(key);const p=researchFresh(address).finally(()=>inFlightResearch.delete(key));inFlightResearch.set(key,p);return p}

module.exports={research,configuredSources:()=>{const a=configs().map(x=>({name:x.name,type:'Authorized MLS / RESO Web API'}));if(process.env.REGRID_API_TOKEN||process.env.REGRID_TOKEN)a.push({name:'Regrid',type:'County / parcel records'});if(process.env.OPENAI_API_KEY)a.push({name:'Better Web Research',type:'Public web search'});return a},cacheKey,_norm:normMls,_parseAddress:parseAddress,_normRegrid:normRegrid,_researchRegrid:researchRegrid,_selectRegridFeature:selectRegridFeature,_addressMatchScore:addressMatchScore,_resolveField:resolveField,_resolveSubjectEvidence:resolveSubjectEvidence};
