/* Better Real Estate authorized property evidence adapters.
   No website scraping. Live MLS access is used only when Admin configures an authorized RESO Web API feed. */
function clean(v,n=300){return String(v??'').trim().slice(0,n)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function esc(v){return String(v).replace(/'/g,"''")}
function hav(a,b,c,d){if([a,b,c,d].some(x=>!Number.isFinite(Number(x))))return null;const R=3958.8,rad=x=>Number(x)*Math.PI/180;const dLat=rad(c-a),dLon=rad(d-b);const q=Math.sin(dLat/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function configs(){
  const out=[];
  if(process.env.MLS_RESO_BASE_URL&&process.env.MLS_RESO_TOKEN) out.push({name:clean(process.env.MLS_RESO_NAME||'Authorized MLS',80),base:clean(process.env.MLS_RESO_BASE_URL,600),token:clean(process.env.MLS_RESO_TOKEN,2000)});
  if(process.env.MLS_RESO_SOURCES_JSON){try{const a=JSON.parse(process.env.MLS_RESO_SOURCES_JSON);for(const x of Array.isArray(a)?a:[]){if(x?.name&&x?.baseUrl&&x?.token)out.push({name:clean(x.name,80),base:clean(x.baseUrl,600),token:clean(x.token,2000)})}}catch{}}
  return out.filter((x,i,a)=>a.findIndex(y=>y.base===x.base)===i);
}
function norm(r,source){return {source,sourceType:'MLS / RESO',listingKey:clean(r.ListingKey||r.ListingId||'',120)||null,address:clean(r.UnparsedAddress||[r.StreetNumber,r.StreetName,r.StreetSuffix].filter(Boolean).join(' '),250)||null,city:clean(r.City,100)||null,state:clean(r.StateOrProvince,40)||null,postalCode:clean(r.PostalCode,20)||null,status:clean(r.StandardStatus||r.MlsStatus,60)||null,listPrice:num(r.ListPrice),salePrice:num(r.ClosePrice),saleDate:r.CloseDate||null,bedrooms:num(r.BedroomsTotal),bathrooms:num(r.BathroomsTotalInteger??r.BathroomsFull),squareFootage:num(r.LivingArea),lotSize:num(r.LotSizeSquareFeet),yearBuilt:num(r.YearBuilt),propertyType:clean(r.PropertyType||r.PropertySubType,100)||null,daysOnMarket:num(r.DaysOnMarket),remarks:clean(r.PublicRemarks,1200)||null,latitude:num(r.Latitude),longitude:num(r.Longitude),sourceUpdatedAt:r.ModificationTimestamp||null,retrievedAt:new Date().toISOString()}}
async function query(cfg,filter,top=100){const base=cfg.base.replace(/\/$/,'');const fields=['ListingKey','ListingId','UnparsedAddress','StreetNumber','StreetName','StreetSuffix','City','StateOrProvince','PostalCode','StandardStatus','MlsStatus','ListPrice','ClosePrice','CloseDate','BedroomsTotal','BathroomsTotalInteger','BathroomsFull','LivingArea','LotSizeSquareFeet','YearBuilt','PropertyType','PropertySubType','DaysOnMarket','PublicRemarks','Latitude','Longitude','ModificationTimestamp'].join(',');const u=new URL(base+'/Property');u.searchParams.set('$filter',filter);u.searchParams.set('$select',fields);u.searchParams.set('$top',String(top));const r=await fetch(u,{headers:{Authorization:`Bearer ${cfg.token}`,Accept:'application/json'}});if(!r.ok)throw new Error(`${cfg.name} returned ${r.status}`);const j=await r.json();return (Array.isArray(j.value)?j.value:[]).map(x=>norm(x,cfg.name))}
function parseAddress(address){const p=String(address).split(',').map(x=>x.trim()).filter(Boolean);const street=p[0]||address,city=p[1]||'',stateZip=p[2]||'';const m=stateZip.match(/^([A-Za-z]{2})\s*(\d{5})?/);return {street,city,state:m?.[1]||'',zip:m?.[2]||''}}
function bestSubject(rows,a){const needle=a.street.toLowerCase();return rows.sort((x,y)=>{const sx=(x.address||'').toLowerCase().includes(needle)?1:0,sy=(y.address||'').toLowerCase().includes(needle)?1:0;return sy-sx})[0]||null}
async function research(address){const sources=configs(),parsed=parseAddress(address),errors=[],allSubjects=[],allComps=[];
  for(const cfg of sources){try{const clauses=[];if(parsed.street)clauses.push(`contains(tolower(UnparsedAddress),'${esc(parsed.street.toLowerCase())}')`);if(parsed.city)clauses.push(`tolower(City) eq '${esc(parsed.city.toLowerCase())}'`);if(parsed.state)clauses.push(`StateOrProvince eq '${esc(parsed.state.toUpperCase())}'`);const rows=await query(cfg,clauses.join(' and '),15);const subject=bestSubject(rows,parsed);if(subject)allSubjects.push(subject);
    if(subject){const c=[];if(subject.city)c.push(`tolower(City) eq '${esc(subject.city.toLowerCase())}'`);if(subject.state)c.push(`StateOrProvince eq '${esc(subject.state.toUpperCase())}'`);c.push(`StandardStatus eq 'Closed'`);const comps=await query(cfg,c.join(' and '),100);for(const x of comps){if(x.listingKey&&x.listingKey===subject.listingKey)continue;x.distanceMiles=hav(subject.latitude,subject.longitude,x.latitude,x.longitude);if(x.salePrice&&(!x.distanceMiles||x.distanceMiles<=5))allComps.push(x)}}
  }catch(e){errors.push({source:cfg.name,error:clean(e.message,180)})}}
  const subject=allSubjects[0]||null;const seen=new Set(),comps=allComps.filter(x=>{const k=x.listingKey||`${(x.address||'').toLowerCase()}|${x.salePrice}|${x.saleDate}`;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>(a.distanceMiles??99)-(b.distanceMiles??99)).slice(0,30);
  return {configured:sources.length>0,sourceCount:sources.length,sources:sources.map(x=>({name:x.name,type:'Authorized MLS / RESO Web API'})),subject,comps,errors,retrievedAt:new Date().toISOString(),notice:sources.length?'Live evidence came only from Admin-configured authorized MLS feeds.':'No authorized live MLS feed is configured yet. Better did not scrape Zillow or an MLS website.'};
}
module.exports={research,configuredSources:()=>configs().map(x=>({name:x.name,type:'Authorized MLS / RESO Web API'})),_norm:norm,_parseAddress:parseAddress};
