/* Better Real Estate property evidence adapters.
   v29.11: Regrid parcel facts + authorized RESO MLS + OpenAI web research.
   No direct website scraping. Web search is discovery/research only; provider terms still apply. */
function clean(v,n=500){return String(v??'').trim().slice(0,n)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function esc(v){return String(v).replace(/'/g,"''")}
function hav(a,b,c,d){if([a,b,c,d].some(x=>!Number.isFinite(Number(x))))return null;const R=3958.8,rad=x=>Number(x)*Math.PI/180,dLat=rad(c-a),dLon=rad(d-b),q=Math.sin(dLat/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function first(...v){return v.find(x=>x!==undefined&&x!==null&&x!=='')??null}
function parseAddress(address){const p=String(address).split(',').map(x=>x.trim()).filter(Boolean),street=p[0]||address,city=p[1]||'',stateZip=p[2]||'',m=stateZip.match(/^([A-Za-z]{2})\s*(\d{5})?/);return {street,city,state:m?.[1]||'',zip:m?.[2]||''}}
function configs(){const out=[];if(process.env.MLS_RESO_BASE_URL&&process.env.MLS_RESO_TOKEN)out.push({name:clean(process.env.MLS_RESO_NAME||'Authorized MLS',80),base:clean(process.env.MLS_RESO_BASE_URL,600),token:clean(process.env.MLS_RESO_TOKEN,2000)});if(process.env.MLS_RESO_SOURCES_JSON){try{for(const x of JSON.parse(process.env.MLS_RESO_SOURCES_JSON)||[]){if(x?.name&&x?.baseUrl&&x?.token)out.push({name:clean(x.name,80),base:clean(x.baseUrl,600),token:clean(x.token,2000)})}}catch{}}return out.filter((x,i,a)=>a.findIndex(y=>y.base===x.base)===i)}
function normMls(r,source){return {source,sourceType:'MLS / RESO',verification:'authorized-listing-feed',listingKey:clean(r.ListingKey||r.ListingId||'',120)||null,address:clean(r.UnparsedAddress||[r.StreetNumber,r.StreetName,r.StreetSuffix].filter(Boolean).join(' '),250)||null,city:clean(r.City,100)||null,state:clean(r.StateOrProvince,40)||null,postalCode:clean(r.PostalCode,20)||null,status:clean(r.StandardStatus||r.MlsStatus,60)||null,listPrice:num(r.ListPrice),salePrice:num(r.ClosePrice),saleDate:r.CloseDate||null,bedrooms:num(r.BedroomsTotal),bathrooms:num(r.BathroomsTotalInteger??r.BathroomsFull),squareFootage:num(r.LivingArea),lotSize:num(r.LotSizeSquareFeet),yearBuilt:num(r.YearBuilt),propertyType:clean(r.PropertyType||r.PropertySubType,100)||null,daysOnMarket:num(r.DaysOnMarket),remarks:clean(r.PublicRemarks,1200)||null,latitude:num(r.Latitude),longitude:num(r.Longitude),sourceUpdatedAt:r.ModificationTimestamp||null,retrievedAt:new Date().toISOString()}}
async function queryMls(cfg,filter,top=100){const base=cfg.base.replace(/\/$/,''),fields=['ListingKey','ListingId','UnparsedAddress','StreetNumber','StreetName','StreetSuffix','City','StateOrProvince','PostalCode','StandardStatus','MlsStatus','ListPrice','ClosePrice','CloseDate','BedroomsTotal','BathroomsTotalInteger','BathroomsFull','LivingArea','LotSizeSquareFeet','YearBuilt','PropertyType','PropertySubType','DaysOnMarket','PublicRemarks','Latitude','Longitude','ModificationTimestamp'].join(','),u=new URL(base+'/Property');u.searchParams.set('$filter',filter);u.searchParams.set('$select',fields);u.searchParams.set('$top',String(top));const r=await fetch(u,{headers:{Authorization:`Bearer ${cfg.token}`,Accept:'application/json'}});if(!r.ok)throw new Error(`${cfg.name} returned ${r.status}`);const j=await r.json();return (Array.isArray(j.value)?j.value:[]).map(x=>normMls(x,cfg.name))}
function bestSubject(rows,a){const needle=a.street.toLowerCase();return rows.sort((x,y)=>Number((y.address||'').toLowerCase().includes(needle))-Number((x.address||'').toLowerCase().includes(needle)))[0]||null}
function regridFields(feature){const p=feature?.properties||{},f=p.fields||p;return {...f,ll_uuid:first(f.ll_uuid,p.ll_uuid),path:first(f.path,p.path)}}
function normRegrid(feature){const f=regridFields(feature);return {source:'Regrid',sourceType:'County / parcel records',verification:'public-record-aggregator',parcelId:first(f.parcelnumb,f.state_parcelnumb,f.ll_uuid),address:first(f.address,f.situs_address,f.headline),city:first(f.scity,f.city),state:first(f.state2,f.state),postalCode:first(f.szip,f.zip),bedrooms:num(first(f.num_bedrooms,f.bedrooms)),bathrooms:num(first(f.num_bath,f.bathrooms)),squareFootage:num(first(f.recrdareano,f.area_building,f.bldg_sqft,f.building_sqft,f.livingarea,f.living_area,f.ll_bldg_footprint_sqft)),lotSize:num(first(f.ll_gissqft,f.lot_sqft)),yearBuilt:num(f.yearbuilt),propertyType:first(f.usedesc,f.usecode,f.structstyle),salePrice:num(f.saleprice),saleDate:first(f.saledate,f.sale_date),assessedValue:num(first(f.parval,f.assessedval,f.assessed_value)),landValue:num(f.landval),improvementValue:num(f.improvval),taxAmount:num(first(f.taxamt,f.tax_amount)),zoning:first(f.zoning_description,f.zoning),owner:first(f.owner),latitude:num(first(f.lat,f.latitude)),longitude:num(first(f.lon,f.longitude)),sourceUpdatedAt:first(f.ll_updated_at,f.ll_last_refresh),retrievedAt:new Date().toISOString(),rawFieldCount:Object.keys(f).length}}
async function researchRegrid(address){const token=clean(process.env.REGRID_API_TOKEN||process.env.REGRID_TOKEN,3000);if(!token)return {configured:false,subject:null,error:null};const u=new URL('https://app.regrid.com/api/v2/parcels/address');u.searchParams.set('query',address);u.searchParams.set('limit','5');u.searchParams.set('return_custom','true');const r=await fetch(u,{headers:{Accept:'application/json','x-regrid-token':token}});if(!r.ok)throw new Error(`Regrid returned ${r.status}`);const j=await r.json(),features=j?.parcels?.features||j?.features||[];return {configured:true,subject:features[0]?normRegrid(features[0]):null,error:null,count:features.length}}
function extractText(payload){for(const item of payload?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&c.text)return c.text;return ''}
function webSources(payload){const urls=[];for(const item of payload?.output||[]){if(item?.type==='web_search_call')for(const s of item?.action?.sources||[])if(s?.url)urls.push(s.url);for(const c of item?.content||[])for(const a of c?.annotations||[])if(a?.url)urls.push(a.url)}return [...new Set(urls)].slice(0,30)}
async function researchWeb(address){const key=clean(process.env.OPENAI_API_KEY,3000);if(!key)return {configured:false,facts:null,comps:[],sources:[],error:null};const schema={type:'object',additionalProperties:false,required:['facts','soldComps','marketContext','notes'],properties:{facts:{type:'object',additionalProperties:false,required:['bedrooms','bathrooms','squareFootage','yearBuilt','propertyType','lastSalePrice','lastSaleDate'],properties:{bedrooms:{anyOf:[{type:'number'},{type:'null'}]},bathrooms:{anyOf:[{type:'number'},{type:'null'}]},squareFootage:{anyOf:[{type:'number'},{type:'null'}]},yearBuilt:{anyOf:[{type:'number'},{type:'null'}]},propertyType:{anyOf:[{type:'string'},{type:'null'}]},lastSalePrice:{anyOf:[{type:'number'},{type:'null'}]},lastSaleDate:{anyOf:[{type:'string'},{type:'null'}]}}},soldComps:{type:'array',maxItems:12,items:{type:'object',additionalProperties:false,required:['address','salePrice','saleDate','bedrooms','bathrooms','squareFootage','yearBuilt','propertyType','sourceUrl'],properties:{address:{type:'string'},salePrice:{type:'number'},saleDate:{type:'string'},bedrooms:{anyOf:[{type:'number'},{type:'null'}]},bathrooms:{anyOf:[{type:'number'},{type:'null'}]},squareFootage:{anyOf:[{type:'number'},{type:'null'}]},yearBuilt:{anyOf:[{type:'number'},{type:'null'}]},propertyType:{anyOf:[{type:'string'},{type:'null'}]},sourceUrl:{type:'string'}}}},marketContext:{type:'array',maxItems:10,items:{type:'object',additionalProperties:false,required:['address','status','price','sourceUrl'],properties:{address:{type:'string'},status:{type:'string'},price:{anyOf:[{type:'number'},{type:'null'}]},sourceUrl:{type:'string'}}}},notes:{type:'array',maxItems:8,items:{type:'string'}}}};
 const body={model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high'}],tool_choice:'required',instructions:'Research a residential real-estate property using public web search. Use reliable sources and multiple independent sources when possible: county/assessor/public records, broker/MLS-syndicated listing pages, reputable real-estate portals, and recorded-sale pages. Do not bypass paywalls, authentication, robots controls, or access restrictions. Do not invent facts. Search specifically for the exact subject address, its public property facts, sale/listing history, and recent nearby SOLD comparable properties. Active/pending listings are market context only, never sold comps. A sold comp must have an exact address, sale price, sale date and source URL; omit it otherwise. Return null for unverified facts.',input:`Subject property: ${address}`,text:{format:{type:'json_schema',name:'better_property_web_research',schema,strict:true}},max_output_tokens:2200};
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Web research failed (${r.status}): ${clean(j?.error?.message||'unknown error',180)}`);let parsed=null;try{parsed=JSON.parse(extractText(j))}catch{};if(!parsed)return {configured:true,facts:null,comps:[],sources:webSources(j),error:'Web research returned no structured evidence.'};const comps=(parsed.soldComps||[]).map(x=>({...x,source:'Public web research',sourceType:'Public web',verification:'web-corroborated',retrievedAt:new Date().toISOString()}));return {configured:true,facts:parsed.facts,comps,marketContext:parsed.marketContext||[],notes:parsed.notes||[],sources:webSources(j),error:null}}
function chooseSubject(mls,regrid,web,address){const w=web?.facts||{};const base=mls?{...mls}:regrid?{...regrid}:{address,source:'Web research',sourceType:'Public web'};for(const [k,v] of Object.entries({bedrooms:w.bedrooms,bathrooms:w.bathrooms,squareFootage:w.squareFootage,yearBuilt:w.yearBuilt,propertyType:w.propertyType,salePrice:w.lastSalePrice,saleDate:w.lastSaleDate}))if((base[k]===null||base[k]===undefined||base[k]==='')&&v!==null&&v!==undefined&&v!=='')base[k]=v;return base}
async function research(address){const parsed=parseAddress(address),errors=[],allSubjects=[],allComps=[],sources=[];let regrid={configured:false,subject:null},web={configured:false,facts:null,comps:[],sources:[]};
 try{regrid=await researchRegrid(address);if(regrid.configured)sources.push({name:'Regrid',type:'County / parcel records'});if(regrid.subject)allSubjects.push(regrid.subject)}catch(e){errors.push({source:'Regrid',error:clean(e.message,180)})}
 for(const cfg of configs()){sources.push({name:cfg.name,type:'Authorized MLS / RESO Web API'});try{const clauses=[];if(parsed.street)clauses.push(`contains(tolower(UnparsedAddress),'${esc(parsed.street.toLowerCase())}')`);if(parsed.city)clauses.push(`tolower(City) eq '${esc(parsed.city.toLowerCase())}'`);if(parsed.state)clauses.push(`StateOrProvince eq '${esc(parsed.state.toUpperCase())}'`);const rows=await queryMls(cfg,clauses.join(' and '),15),subject=bestSubject(rows,parsed);if(subject)allSubjects.unshift(subject);if(subject){const c=[];if(subject.city)c.push(`tolower(City) eq '${esc(subject.city.toLowerCase())}'`);if(subject.state)c.push(`StateOrProvince eq '${esc(subject.state.toUpperCase())}'`);c.push(`StandardStatus eq 'Closed'`);for(const x of await queryMls(cfg,c.join(' and '),100)){if(x.listingKey&&x.listingKey===subject.listingKey)continue;x.distanceMiles=hav(subject.latitude,subject.longitude,x.latitude,x.longitude);if(x.salePrice&&(!x.distanceMiles||x.distanceMiles<=5))allComps.push(x)}}}catch(e){errors.push({source:cfg.name,error:clean(e.message,180)})}}
 try{web=await researchWeb(address);if(web.configured)sources.push({name:'Better Web Research',type:'Public web search'});allComps.push(...(web.comps||[]))}catch(e){errors.push({source:'Better Web Research',error:clean(e.message,180)})}
 const mlsSubject=allSubjects.find(x=>x.sourceType==='MLS / RESO')||null,subject=chooseSubject(mlsSubject,regrid.subject,web,address),seen=new Set(),comps=allComps.filter(x=>{const k=x.listingKey||`${clean(x.address).toLowerCase()}|${x.salePrice}|${x.saleDate}`;if(!x.salePrice||seen.has(k))return false;seen.add(k);if(subject?.latitude&&subject?.longitude&&x.latitude&&x.longitude)x.distanceMiles=hav(subject.latitude,subject.longitude,x.latitude,x.longitude);return true}).sort((a,b)=>(a.distanceMiles??99)-(b.distanceMiles??99)).slice(0,30);
 const conflicts=[];for(const k of ['bedrooms','bathrooms','squareFootage','yearBuilt']){const vals=[mlsSubject?.[k],regrid.subject?.[k],web.facts?.[k]].filter(v=>v!==null&&v!==undefined&&v!=='');if(new Set(vals.map(String)).size>1)conflicts.push({field:k,values:{mls:mlsSubject?.[k]??null,regrid:regrid.subject?.[k]??null,web:web.facts?.[k]??null}})}
 return {configured:sources.length>0,sourceCount:sources.length,sources,subject,comps,marketContext:web.marketContext||[],webSources:web.sources||[],conflicts,errors,retrievedAt:new Date().toISOString(),notice:`Research checked ${sources.map(x=>x.name).join(', ')||'no live sources'}. ${configs().length?'Authorized MLS feeds were queried.':'No authorized MLS feed is configured.'} ${regrid.configured?'Regrid parcel records were queried.':'Regrid is not configured.'} ${web.configured?'Public web research was performed.':'Web research was unavailable.'}`};
}
module.exports={research,configuredSources:()=>{const a=configs().map(x=>({name:x.name,type:'Authorized MLS / RESO Web API'}));if(process.env.REGRID_API_TOKEN||process.env.REGRID_TOKEN)a.push({name:'Regrid',type:'County / parcel records'});if(process.env.OPENAI_API_KEY)a.push({name:'Better Web Research',type:'Public web search'});return a},_norm:normMls,_parseAddress:parseAddress,_normRegrid:normRegrid,_researchRegrid:researchRegrid};
