const assert=require('assert'),vm=require('vm'),fs=require('fs');
const source=fs.readFileSync('public/meta-pixel.js','utf8');
function setup(extra={}){const values=new Map(),scripts=[];const window={location:{href:'https://betterrealestate.org/',pathname:'/',search:''},navigator:{},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},addEventListener(){},...extra};const document={createElement:()=>({}),getElementsByTagName:()=>[{parentNode:{insertBefore:s=>scripts.push(s)}}]};vm.runInNewContext(source,{window,document,URLSearchParams});return {window,scripts,values};}
const env=setup();env.window.BetterPixel.update({view:'admin',signedIn:true});assert.equal(env.scripts.length,0);env.window.BetterPixel.update({view:'home',signedIn:false});assert.equal(env.scripts.length,1);let pageviews=()=>env.window.fbq.queue.filter(a=>a[0]==='trackSingle'&&a[2]==='PageView');assert.equal(pageviews().length,1);assert.equal(pageviews()[0][1],'1783797429493375');assert(env.window.fbq.queue.some(a=>a[0]==='set'&&a[1]==='autoConfig'&&a[2]===false));env.window.BetterPixel.update({view:'home',signedIn:false});assert.equal(pageviews().length,1);env.window.BetterPixel.disable();env.window.BetterPixel.update({view:'home',signedIn:false});assert.equal(pageviews().length,1);env.window.BetterPixel.enable();assert.equal(pageviews().length,2);env.window.location.search='?verify=secret';env.window.location.href+='?verify=secret';env.window.BetterPixel.update({view:'home',signedIn:false});assert.equal(pageviews().length,2,'token URLs must not be tracked');
for(const view of ['auth','admin','settings','wallet','chat','dealbuilder','compose','detail','verify','reset']){const e=setup();e.window.BetterPixel.update({view,signedIn:false});assert.equal(e.scripts.length,0,view);}
for(const navigator of [{globalPrivacyControl:true},{doNotTrack:'1'}]){const e=setup({navigator});e.window.BetterPixel.update({view:'home',signedIn:false});assert.equal(e.scripts.length,0);}
const account=setup();account.window.BetterPixel.update({view:'home',signedIn:false,adMeasurement:false});assert.equal(account.scripts.length,0);assert.equal(account.values.get('bre-ad-measurement-v1'),'decline');
assert(!fs.readFileSync('public/index.html','utf8').includes('facebook.com/tr?'),'no ungated noscript request');
console.log('v29.49 Pixel ID, single PageView, auto-data off, private/token exclusion, opt-out/account setting and browser privacy signal checks: PASS');
