const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const pkg = require(path.join(root, 'package.json'));
const app = fs.readFileSync(path.join(root, 'public/app.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const store = fs.readFileSync(path.join(root, 'store.js'), 'utf8');
assert(['2.9.29','2.9.30','2.9.31','2.9.32','2.9.33','2.9.34','2.9.35','2.9.36','2.9.37','2.9.38','2.9.39','2.9.40'].includes(pkg.version));
assert(app.includes('detailPreview: null'), 'detail preview state missing');
assert(app.includes('renderDetailPreview'), 'instant detail preview renderer missing');
assert(app.includes("app.replaceChildren(rendered)"), 'detail hydration replacement missing');
assert(app.includes("openListingDetail(l, idx)"), 'feed cards must pass their already-loaded listing into details');
assert(app.includes("'/api/listings/' + encodeURIComponent(id) + '/view'"), 'nonblocking view analytics call missing');
assert(server.includes("app.post('/api/listings/:id/view'"), 'isolated view endpoint missing');
const detailRoute = server.slice(server.indexOf("app.get('/api/listings/:id'"), server.indexOf("app.post('/api/listings/:id/unlock'"));
assert(!detailRoute.includes('await saveDB(db)'), 'property GET must not block on analytics persistence');
assert(store.includes('async function appendRecord'), 'single-record persistence helper missing');
assert(store.includes('appendRecord, sql'), 'appendRecord must be exported');
console.log('v29.21 instant property details regression: PASS');
