const assert=require('assert'),fs=require('fs'),di=require('../dealIntelligence');
const app=fs.readFileSync('public/app.js','utf8');
const helper=app.slice(app.indexOf('function dealValuationPrecision('),app.indexOf('\nasync function renderDealBuilder()')).trim();
assert.equal(helper,di.dealValuationPrecision.toString());
const fixture=require('./fixtures/v29-40-bennington.json');
const subject={bedrooms:4,bathrooms:2.5,squareFootage:1796,yearBuilt:1970,propertyType:'Townhouse'};
const ca=di.analyzeComps(subject,fixture.compGate.selected);
assert(ca.indicativeReady);assert(!ca.valuationReady);assert.equal(ca.precision,'working_range');assert.equal(ca.confidence,'Low');assert(ca.workingEstimate>=415210&&ca.workingEstimate<=467111);
const ev={identity:fixture.identity,fieldEvidence:fixture.fieldEvidence,subject};
assert.equal(di.dealValuationPrecision(ev,ca),'working_range');
assert.equal(di.dealValuationPrecision({...ev,identity:{addressMatched:false}},ca),'withheld');
assert.equal(di.dealValuationPrecision({...ev,fieldEvidence:{...ev.fieldEvidence,bathrooms:{status:'conflicting'}}},ca),'withheld');
assert.equal(di.dealValuationPrecision({...ev,fieldEvidence:{...ev.fieldEvidence,squareFootage:{status:'recorded',recordedValue:1796}}},ca),'withheld');
assert.equal(di.dealValuationPrecision(ev,{...ca,valuationReady:true}),'working_range');
assert.equal(di.dealValuationPrecision({...ev,identity:{...ev.identity,sufficientForValuation:true}},{...ca,valuationReady:true}),'precise');
const weak=fixture.compGate.selected.map(x=>({...x,corroboratingSourceFamilies:[x.sourceFamily]}));assert(!di.analyzeComps(subject,weak).indicativeReady);
assert(!di.analyzeComps(subject,fixture.compGate.selected.slice(0,2)).indicativeReady);
const rejected={...fixture.compGate.selected[0],address:'Wrong type',propertyType:'Single family'};const screened=di.analyzeComps(subject,[...fixture.compGate.selected,rejected]);assert(screened.excluded.some(x=>x.address==='Wrong type'&&x.reasons.includes('non-comparable property type')));
assert(app.includes('release:62'));console.log('v29.40 production comp fixture, corroborated working range, shared subject precision and excluded reasons: PASS');
