const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public/style.css'),'utf8');
const pkg=require('../package.json');
assert.equal(pkg.version,'2.9.32');
assert(app.includes("'torso','/mascot-v2/torso.webp'"));
for(const p of ['head','muzzle','ear-left','ear-right','arm-left','arm-right','paw-left','paw-right','tail'])assert(app.includes(`/mascot-v2/${p}.webp`),`missing ${p}`);
assert(app.includes("data-life':'articulated-v2'"),'new articulated rig marker missing');
assert(app.includes('mascot-joint-local mascot-paw-left'),'left paw hierarchy missing');
assert(app.includes('mascot-joint-local mascot-muzzle'),'muzzle hierarchy missing');
assert(app.includes('m.gaze.x+=')&&app.includes('dt*2.1'),'slow damped gaze missing');
assert(app.includes('m.nextIdle=now+6500+Math.random()*5500'),'idle pauses missing');
assert(!app.includes('BETTER_MASCOT_POSES'),'slideshow pose map must stay gone');
assert(!app.includes('Need help posting, learning'),'removed help phrase returned');
assert(!app.includes('/mascot-rig/'),'old forbidden-pose rig must not be referenced');
assert(css.includes('.mascot-articulated-stage'),'articulated stage CSS missing');
assert(css.includes('transform-origin:27% 54%'),'left shoulder joint missing');
assert(css.includes('transform-origin:75% 54%'),'right shoulder joint missing');
assert(css.includes('place-items:end center'),'header baseline anchoring missing');
assert(css.includes('@media(prefers-reduced-motion:reduce)'),'reduced motion missing');
const logoA=fs.readFileSync(path.join(root,'BRE- Logo.png')),logoB=fs.readFileSync(path.join(root,'public','better-guide-logo.png'));
const h=x=>crypto.createHash('sha256').update(x).digest('hex');assert.equal(h(logoA),h(logoB),'canonical Better logo changed');
console.log('v29.32 articulated header mascot regression: PASS');
