const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('public/app.js','utf8');
const css = fs.readFileSync('public/style.css','utf8');
const pkg = require('../package.json');
assert(['2.9.29','2.9.30','2.9.31','2.9.32','2.9.33','2.9.34'].includes(pkg.version));
assert(app.includes('function renderSettings() {'), 'Settings should render synchronously from already-loaded user state');
assert(!app.includes('async function renderSettings() {'), 'Settings must not block on secondary preferences');
assert(app.includes("api('GET', '/api/email-preferences').then(ep =>"), 'Email preferences should hydrate after Settings paints');
assert(app.includes('function propertyShareCaption(listing)'), 'property share caption builder missing');
assert(app.includes('openPropertyShare(l)'), 'feed property Share should open prepared post');
assert(app.includes('propertyShareBar(listing)'), 'detail property share should use prepared post UI');
assert(app.includes('Looking to connect with buyers interested in this property.'), 'connection-first property copy missing');
assert(!app.includes("shareStrip({ kind: 'property'"), 'generic property share strip should not remain');
assert(app.includes("load();return wrap;"), 'search should paint before its first network result returns');
for (const token of ['--border:','--panel2:','--ink-muted:','--accent-line:','--danger:']) assert(css.includes(token), `compatibility token ${token} missing`);
assert(css.includes('.property-share-overlay') && css.includes('.property-share-card'), 'share modal presentation missing');
assert(css.includes('env(safe-area-inset-bottom)'), 'share modal must respect mobile safe area');
console.log('v29.24 conservative site cleanup + property sharing regression: PASS');
