const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../server.js'),'utf8');
const route=source.slice(source.indexOf("app.get('/api/admin/activity'"),source.indexOf("app.get('/api/admin/user-inspector'"));
let handler;
vm.runInNewContext(route,{app:{get:(path,auth,admin,fn)=>{assert.equal(path,'/api/admin/activity');assert.equal(auth,'auth');assert.equal(admin,'admin');handler=fn}},requireAuth:'auth',requireAdmin:'admin',Date,Set,Number,String,Object,Math,isDemoUser:u=>!!u.demo,safeActivityUser:u=>({...u,markets:[]}),actualPlanLabel:()=> 'Free',isPro:()=>false,isPlatinum:()=>false,isWholesale:()=>false,activityWindowMs:{'24h':86400000,'7d':7*86400000,'30d':30*86400000}});
const now=Date.now(),old=new Date(now-400*86400000).toISOString(),recent=new Date(now-1000).toISOString();
const db={users:[{id:'old',lastActiveAt:old,createdAt:old},{id:'event',createdAt:old},{id:'new',lastActiveAt:recent,createdAt:recent},{id:'never',createdAt:old},{id:'invalid',lastActiveAt:'bad'},{id:'demo',demo:true,lastActiveAt:recent,createdAt:recent}],activityEvents:[{userId:'event',at:old},{userId:'old',at:old},{userId:'demo',at:recent}],listings:[{ownerId:'old',createdAt:old},{ownerId:'demo',createdAt:recent},{ownerId:'old'}],messages:[{fromUserId:'old',toUserId:'new',at:old}],dealAnalyses:[{userId:'old',createdAt:old}],saves:[]};
async function run(query){let out;await handler({query,db},{json:o=>out=o});return out}
(async()=>{const all=await run({preset:'all'});assert.equal(all.metrics.uniqueActive,3);assert.equal(all.metrics.signups,4);assert.equal(all.metrics.listings,1);assert.equal(all.metrics.messages,1);assert.equal(all.metrics.dealBuilderRuns,1);assert.equal(all.metrics.activeNow,1);assert.ok(all.historyNote.includes('pruned'));assert.equal(all.start,'1970-01-01T00:00:00.000Z');const day=await run({preset:'24h'});assert.equal(day.metrics.uniqueActive,1);assert.equal(day.metrics.listings,0);const custom=await run({preset:'custom',start:new Date(now-401*86400000).toISOString(),end:new Date(now-399*86400000).toISOString()});assert.equal(custom.metrics.uniqueActive,2);assert.equal(custom.metrics.listings,1);console.log('v29.43 all-time, dated presets, demo exclusion and missing timestamps: PASS')})().catch(e=>{console.error(e);process.exitCode=1});
