const fs=require('fs'),vm=require('vm'),assert=require('assert'),communications=require('../communications'),ds=require('../dealSources');
const app=fs.readFileSync('public/app.js','utf8'),server=fs.readFileSync('server.js','utf8');
const c={state:{view:'detail',composeEditId:'old',composePhotos:['old'],dealBuilderDraft:{address:'old'}},writeRoute(){},window:{scrollTo(){}},render(){}};vm.createContext(c);vm.runInContext(app.slice(app.indexOf('function go(')).split('\n')[0],c);
c.go('compose');assert.equal(c.state.composeEditId,null);assert.equal(c.state.dealBuilderDraft,null);assert.equal(c.state.composePhotos.length,0);
c.go('compose',{composeEditId:'edit-id'});assert.equal(c.state.composeEditId,'edit-id');c.go('feed');c.go('compose');assert.equal(c.state.composeEditId,null);
c.go('compose',{dealBuilderDraft:{address:'explicit draft'}});assert.equal(c.state.dealBuilderDraft.address,'explicit draft');assert.equal(c.state.composeEditId,null);
const eligible={id:'a',role:'buyer',emailVerified:true,marketingOptIn:true},db={users:[eligible,{...eligible,id:'b'},{...eligible,id:'c',marketingOptIn:false},{...eligible,id:'d',emailVerified:false},{...eligible,id:'e',marketingUnsubscribedAt:'2026-10-07'},{...eligible,id:'f',demo:true}]};
assert.deepEqual(communications.eligibleBroadcastUsers(db,{kind:'selected',userIds:['b','c','d','e','f','missing']}).map(u=>u.id),['b']);assert.equal(communications.eligibleBroadcastUsers(db,{kind:'selected',userIds:[]}).length,0);assert.equal(communications.eligibleBroadcastUsers(db,{kind:'unknown'}).length,0);
const input={subject:'Subject',headline:'Headline',body:'Body',audience:{kind:'selected',userIds:['b','b'],market:'ignored'}};const normalized=communications.normalizeBroadcastInput(input);assert.deepEqual(normalized.audience,{kind:'selected',market:'',userIds:['b']});assert.throws(()=>communications.normalizeBroadcastInput({...input,audience:{kind:'selected',userIds:[]}}));assert.throws(()=>communications.normalizeBroadcastInput({...input,audience:{kind:'selected',userIds:Array.from({length:201},(_,i)=>String(i))}}));
assert(server.includes("app.get('/api/admin/email-center/recipients', requireAuth, requireAdmin"));assert(server.includes('No eligible recipients selected.'));
assert.equal(ds._norm({BathroomsTotalInteger:2,BathroomsFull:1,BathroomsHalf:1},'MLS').bathrooms,1.5);assert.equal(ds._norm({BathroomsTotalDecimal:2.5,BathroomsFull:2,BathroomsHalf:1},'MLS').bathrooms,2.5);assert.equal(ds._norm({},'MLS').bathrooms,null);
assert(ds._urlWasActuallySearched('https://example.org/property?id=1&utm_source=test',['https://www.example.org/property?id=1']));assert(!ds._urlWasActuallySearched('https://example.org/property?id=1',['https://example.org/property?id=2']));
(async()=>{const old=global.fetch,key=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='fixture-only';try{
 const sources=Array.from({length:55},(_,i)=>({url:`https://portal${i}.example/1308-faxon`}));
 const facts=[{field:'bedrooms',numberValue:3,textValue:null,subjectAddress:'1308 Faxon Ave, Memphis, TN 38104',sourceUrl:sources[51].url,sourceName:'Fixture portal',sourceKind:'real_estate_portal',pageTitle:'Fixture',evidenceText:'3 bedrooms'},{field:'bathrooms',numberValue:1.5,textValue:null,subjectAddress:'1308 Faxon Ave, Memphis, TN 38104',sourceUrl:sources[52].url,sourceName:'Fixture portal',sourceKind:'real_estate_portal',pageTitle:'Fixture',evidenceText:'1.5 bathrooms'}];
 global.fetch=async()=>({ok:true,json:async()=>({output:[{type:'web_search_call',action:{sources}},{type:'message',content:[{type:'output_text',text:JSON.stringify({factEvidence:facts,soldComps:[],conditionEvidence:[],marketContext:[],notes:[]})}]}]})});
 const r=await ds._researchWeb('1308 Faxon Ave, Memphis, TN 38104',{needFacts:true,needComps:false});assert.equal(r.sources.length,55);assert.equal(r.factEvidence.length,2);assert.equal(r.facts.bathrooms,1.5);assert.equal(r.diagnostic.rejectedFactRows,0);
 const resolved=ds._resolveSubjectEvidence({address:'1308 Faxon Ave, Memphis, TN 38104',web:r});assert.equal(resolved.subject.bedrooms,null);assert.equal(resolved.fieldEvidence.bedrooms.status,'recorded');assert.equal(resolved.fieldEvidence.bedrooms.recordedValue,3);
 }finally{global.fetch=old;if(key===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=key;}console.log('v29.38 fresh Post, selected-recipient eligibility, sourced facts and partial baths: PASS');})().catch(e=>{console.error(e);process.exitCode=1});
