const fs=require('fs');
const path=require('path');
const assert=require('assert');
const app=fs.readFileSync('public/app.js','utf8');
const css=fs.readFileSync('public/style.css','utf8');
const pkg=require('../package.json');
assert.equal(pkg.version,'2.9.31');
for(const token of ['function mascotSpringStep','function mascotLifeFrame','function mascotIdlePlan','function aimBetterMascotAt','respondToPointer','respondToAction','respondToScroll']) assert(app.includes(token),token+' missing');
for(const token of ['--head-x','--body-r','--paw-r','--tail-r','.mascot-head','.mascot-paw','.mascot-tail']) assert(css.includes(token),token+' missing');
assert(app.includes("title:'The mascot now reacts continuously'"),'tutorial update missing');
assert(!app.includes('Need help posting, learning'),'removed mascot bubble copy returned');
assert(!app.includes('BETTER_MASCOT_POSES'),'slideshow system returned');
for(const part of ['body','head','ear-left','ear-right','paw','tail']) assert(fs.existsSync(path.join(__dirname,'..','public','mascot-rig',part+'.webp')),part+' rig asset missing');
console.log('v29.31 true live rig regression: PASS');
