const assert=require('assert'),fs=require('fs'),crypto=require('crypto');
const {isAffiliateOnlyUser}=require('../affiliateAccounts');
const {verificationReminderDue,createVerificationReminderRunner,INTERVAL_MS}=require('../verificationReminders');
const {registerAffiliateProspects,prospectFields}=require('../affiliateProspects');
const source=fs.readFileSync('server.js','utf8'),FOUNDER_PROGRAM_LIMIT=50,FOUNDER_PLATINUM_DAYS=14,isAdminUser=u=>u?.role==='admin';
for(const name of ['founderProgramEligible','ensureFirst100FounderProgram'])eval(source.match(new RegExp(`function ${name}\\([^]*?\\n\\}`))[0]);
const start='2026-01-01T00:00:00Z',end='2026-01-15T00:00:00Z';
const users=Array.from({length:51},(_,i)=>({id:'u'+i,name:'User '+i,email:'u'+i+'@example.invalid',role:i===0?'affiliate':'buyer',createdAt:new Date(Date.parse(start)+i*1000).toISOString(),foundingMember:i<50,foundingMemberSource:i<50?'first50':null,founderLaunchPosition:i<50?i+1:null,founderPlatinumUntil:i<50?end:null,plan:i===0?'platinum':'free',planUntil:'2030-01-01',grantPlan:'pro',grantUntil:'2030-01-01'}));
const db={users,founderAwards:users.slice(0,50).map(u=>({id:'award-'+u.id,userId:u.id,signupAt:u.createdAt,awardedAt:start,platinumStartsAt:start,platinumUntil:end}))};
assert(ensureFirst100FounderProgram(db));assert.equal(users[0].foundingMember,false);assert.equal(users[0].founderPlatinumUntil,null);assert.equal(users[0].plan,'platinum');assert.equal(users[0].grantPlan,'pro');assert.equal(users[1].founderLaunchPosition,1);assert.equal(users[50].founderLaunchPosition,50);assert.equal(db.founderAwards.filter(x=>!x.limitExcludedAt).length,50);assert.equal(ensureFirst100FounderProgram(db),false);
const retired=db.founderAwards.find(x=>x.userId==='u0');assert.equal(retired.platinumUntil,end);users[0].role='buyer';ensureFirst100FounderProgram(db);assert.equal(users[0].founderPlatinumUntil,end,'returning to real estate must not renew original bonus');
assert.throws(()=>prospectFields({stage:'paid'}));assert.throws(()=>prospectFields({nextFollowUp:'wrong'}));assert.throws(()=>prospectFields({name:''}));
const routes={};registerAffiliateProspects({get:(p,...h)=>routes['GET '+p]=h,post:(p,...h)=>routes['POST '+p]=h,patch:(p,...h)=>routes['PATCH '+p]=h,delete:(p,...h)=>routes['DELETE '+p]=h},{requireAuth:()=>{},saveDB:async()=>{},crypto});
const data={users:[],affiliateApplications:[],affiliateProspects:[]},owner={id:'owner',role:'affiliate'},stranger={id:'stranger',role:'affiliate'};
const run=async(method,path,user,body={},params={})=>{let status=200,payload;const req={db:data,user,body,params};const res={status:n=>{status=n;return res},json:x=>{payload=x;return res}};const h=routes[method+' '+path];let allowed=false;h[1](req,res,()=>allowed=true);if(allowed)await h[2](req,res);return {status,payload};};
(async()=>{
const made=await run('POST','/api/affiliate/prospects',owner,{name:'Contact',userId:'stranger',stage:'interested'});assert.equal(made.payload.prospect.userId,'owner');const id=made.payload.prospect.id;
assert.equal((await run('GET','/api/affiliate/prospects',stranger)).payload.prospects.length,0);
assert.equal((await run('PATCH','/api/affiliate/prospects/:id',stranger,{stage:'joined'},{id})).status,404);
assert.equal((await run('DELETE','/api/affiliate/prospects/:id',stranger,{}, {id})).status,404);
assert.equal((await run('GET','/api/affiliate/prospects',{id:'buyer',role:'buyer'})).status,403);
assert.equal((await run('GET','/api/affiliate/prospects',{...owner,demo:true})).status,403);
assert.equal((await run('PATCH','/api/affiliate/prospects/:id',owner,{stage:'contacted'},{id})).payload.prospect.stage,'contacted');
assert.equal((await run('DELETE','/api/affiliate/prospects/:id',owner,{}, {id})).status,200);
let now=Date.parse('2026-10-10T00:00:00Z'),stored={users:[{id:'due',email:'due@example.invalid',createdAt:new Date(now-INTERVAL_MS).toISOString(),emailVerified:false,marketingOptIn:false},{id:'recent',email:'recent@example.invalid',createdAt:new Date(now-INTERVAL_MS+1).toISOString()},{id:'verified',email:'verified@example.invalid',createdAt:start,emailVerified:true},{id:'demo',email:'demo@example.invalid',createdAt:start,demo:true},{id:'admin',email:'admin@example.invalid',createdAt:start,role:'admin'}],tokens:[]};
assert(verificationReminderDue(stored.users[0],now));assert(!verificationReminderDue(stored.users[1],now));assert(!verificationReminderDue({email:'x',createdAt:'wrong'},now));
const sent=[];const store={FILE_MODE:true,loadDB:async()=>JSON.parse(JSON.stringify(stored)),saveDB:async x=>stored=JSON.parse(JSON.stringify(x)),appendRecord:async(c,r)=>stored[c].push(r)};
const runner=createVerificationReminderRunner({store,mailer:{configured:()=>true,sendVerification:async(email,name,token)=>{assert(stored.tokens.some(x=>x.token===token));sent.push(email);}},clock:()=>now});
assert.equal((await runner()).sent,1);assert.equal(sent[0],'due@example.invalid');assert.equal((await runner()).sent,0);stored.users[1].emailVerified=true;now+=INTERVAL_MS-1;assert.equal((await runner()).sent,0);now+=1;assert.equal((await runner()).sent,1);stored.users[0].emailVerified=true;now+=INTERVAL_MS;assert.equal((await runner()).sent,0);
stored.users.push({id:'fail',email:'fail@example.invalid',createdAt:start});const failRunner=createVerificationReminderRunner({store,mailer:{configured:()=>true,sendVerification:async()=>{throw Error('mock failure');}},clock:()=>now});assert.equal((await failRunner()).failed,1);assert.equal((await failRunner()).failed,0,'failed delivery must not retry every scheduled tick');
console.log('v29.45 founder exclusion/refill/original dates/paid grants, private prospect CRUD/auth, verification 48h boundary/dedup/stop/failure cooldown: PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
