'use strict';
const fs=require('fs'), path=require('path'), assert=require('assert');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public/style.css'),'utf8');
assert(server.includes('const AFFILIATE_HOLD_DAYS = 3;'),'affiliate hold must be 3 days');
assert(server.includes("version:'2026-09-27-v3'"),'affiliate terms must be versioned v3');
assert(server.includes("kind:'membership_acquisition'"),'commissions must be typed as membership acquisition');
assert(server.includes("c.customerUserId===user.id&&c.kind==='membership_acquisition'"),'must block repeat commission by referred customer, not invoice id');
assert(app.includes('30% one-time cash commission'),'affiliate UI must clearly say one-time');
assert(app.includes('Self-referrals, duplicate or fake accounts') && app.includes('Future material commission changes require affirmative in-platform acceptance'),'affiliate acceptance must show material terms clearly');
assert(app.includes('renewals do not earn another commission'),'affiliate acceptance UI must disclose no renewal commission');
assert(app.includes('BETTER CREDITS') && app.includes('never cash-withdrawable'),'wallet must clearly distinguish Better Credits');
assert(app.includes('SELLER PROCEEDS EARNED') && app.includes('Real cash from your marketplace sales'),'seller proceeds must be clearly cash');
assert(css.includes('.wallet-balance-grid'),'cash/credit wallet presentation must be styled');
assert(app.includes('const TUTORIAL_VERSION = 67;')||app.includes('const TUTORIAL_VERSION = 67;') && app.includes("release:35,title:'Affiliate Wallet'") && app.includes("release:35,title:'Cash and credits'"),'tutorial v35 must teach changed cash/credit behavior');
assert(!server.includes('const AFFILIATE_HOLD_DAYS = 14;'),'old hold must not survive');
console.log('v29.2 affiliate/seller wallet acceptance passed');
