const fs=require('fs');const assert=require('assert');
const server=fs.readFileSync('server.js','utf8');
const app=fs.readFileSync('public/app.js','utf8');
const css=fs.readFileSync('public/style.css','utf8');
const store=fs.readFileSync('store.js','utf8');
const social=fs.readFileSync('social.js','utf8');
const handoff=fs.readFileSync('HANDOFF-V29.md','utf8');
assert(server.includes('const FOUNDER_PROGRAM_LIMIT = 100;')&&server.includes('const FOUNDER_PLATINUM_DAYS = 14;'),'First 100 program must be limited to 100 with 14-day Platinum');
assert(server.includes('function ensureFirst100FounderProgram')&&server.includes('!isAdminUser(user)')&&server.includes("user.demo !== true"),'Founder qualification must be deterministic and exclude admin/demo accounts');
assert(store.includes("'founderAwards'"),'Founder awards must have a durable collection so deleted accounts do not reopen slots');
assert(server.includes('activeFounderPlatinum(user)')&&server.includes('founderPlatinumUntil'),'Founder Platinum must be a separate entitlement');
assert(server.includes('ensureFirst100FounderProgram(db);'),'Signup must run First 100 assignment');
assert(server.includes('if (ensureFirst100FounderProgram(db)) changed = true;'),'Authenticated requests must migrate existing qualifying users safely');
assert(server.includes("app.post('/api/founder-program/acknowledge', requireAuth"),'Founder welcome acknowledgement missing');
assert(server.includes("mode: req.body?.mode === 'extend' ? 'extend' : 'replace'"),'Admin grant endpoint must support extension');
assert(server.includes("if (mode === 'extend')")&&server.includes("revokeReason = 'extended'"),'Grant extension must preserve an audit trail');
assert(app.includes('openAdminAccessModal')&&app.includes('Extend ${adminPlanLabel(u.grant.grantPlan)}')&&app.includes('Replace grant')&&app.includes('Revoke grant'),'Admin access manager must expose grant/replace/extend/revoke');
assert(app.includes('Founder #${u.founderAward.position}')&&app.includes('First 100 Founders'),'Admin must show Founder positions');
assert(app.includes('showFounderWelcome')&&app.includes('Copy invite')&&app.includes('Share founder invite'),'Founder share experience missing');
assert(app.includes('const TUTORIAL_VERSION = 44;')&&app.includes("release:36,title:'Membership access controls'")&&app.includes("release:36,when:()=>!!state.user?.founderLaunchPosition"),'Tutorial v36 must cover the update by access');
assert(css.includes('.admin-access-actions')&&css.includes('align-items:stretch')&&css.includes('.founder-welcome-actions'),'Admin and founder actions need dedicated aligned presentation styles');
assert(css.includes('.membershiprowactions')&&css.includes('white-space:nowrap'),'Membership action buttons must remain level and non-wrapping');
assert(social.includes('founderLaunchPosition'),'Founder position must carry into public profiles');
assert(handoff.includes('First 100')&&(/14[- ]day/i.test(handoff))&&/review the full inherited project rules TWICE/i.test(handoff),'Handoff must preserve launch and build rules');
console.log('v29.4 First 100 + membership access regression: PASS');
