const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),app=fs.readFileSync(path.join(root,'public/app.js'),'utf8'),css=fs.readFileSync(path.join(root,'public/style.css'),'utf8'),pkg=require('../package.json');
assert(['2.9.32','2.9.33','2.9.34','2.9.35','2.9.36','2.9.37','2.9.38','2.9.39','2.9.40','2.9.41','2.9.45','2.9.46','2.9.47','2.9.48'].includes(pkg.version));
assert(app.includes('function createBetterMascotRig'),'articulated mascot factory missing');
assert(app.includes('function mascotLifeFrame'),'live motion controller missing');
assert(app.includes('function aimBetterMascotAt'),'tutorial orientation missing');
assert(!app.includes('BETTER_MASCOT_POSES'),'slideshow pose map must stay gone');
assert(!app.includes('Need help posting, learning'),'removed help phrase returned');
assert(!app.includes('/mascot-rig/'),'old forbidden-pose rig must not be referenced');
assert(css.includes('.mascot-svg .mascot-head')&&css.includes('.mascot-svg .mascot-arm-left'),'articulated joints missing');
assert(css.includes('@media(prefers-reduced-motion:reduce)'),'reduced motion missing');
const logoA=fs.readFileSync(path.join(root,'BRE- Logo.png')),logoB=fs.readFileSync(path.join(root,'public','better-guide-logo.png'));const h=x=>crypto.createHash('sha256').update(x).digest('hex');assert.equal(h(logoA),h(logoB),'canonical Better logo changed');
console.log('v29.32 articulated mascot compatibility regression: PASS');
